name: "Count LaTeX Lines"
description: "Counts the number of lines in .tex files"

inputs:
  filename:
    description: "The .tex file to count lines from"
    required: true
    default: "test.tex"
  output_env:
    description: "Name of the environment variable to store line count"
    required: true
    default: "LINES"
  spreadsheetId:
    description: "ID of the Google Sheet"
    required: true
  worksheetName:
    description: "Worksheet name"
    required: true
  credentials:
    description: "Google credentials JSON"
    required: true
  values:
    description: "Values to append"
    required: true
  range:
    description: "Cell range to write to"
    required: false
    default: "A1"

runs:
  using: "composite"
  steps:
    - name: Count LaTeX lines
      shell: bash
      run: |
        FILE=${{ inputs.filename }}
        ENV_VAR=${{ inputs.output_env }}

        total=$(find . -name "$FILE" -type f -exec wc -l {} + 2>/dev/null | awk '{s+=$1} END {print s}')
        if [ -z "$total" ]; then
          total=0
        fi
        echo "$ENV_VAR=$total" >> $GITHUB_ENV
        echo "LaTeX行数 ($FILE): $total"
