name: "Count LaTeX Lines"
description: "Counts the number of lines in .tex files"
runs:
  using: "composite"
  steps:
    - name: Count LaTeX lines
      shell: bash
      run: |
        # カウントできなかった場合は0にする
        total=$(find . -name "test.tex" -type f -exec wc -l {} + 2>/dev/null | awk '{s+=$1} END {print s}')
        if [ -z "$total" ]; then
          total=0
        fi
        echo "LaTeX行数: $total"
        echo "LINES=$total" >> $GITHUB_ENV
