name: Collect Line Count History

on:
  # 毎日UTCで午前0時に実行
  #schedule:
  #  - cron: '0 0 * * *'
  # GitHub Actionsの画面から手動実行できるようにする
  workflow_dispatch:
  # mainブランチへのプッシュ時にも実行したい場合は追加
  push:
    branches: [ master ]

jobs:
  collect_data:
    runs-on: ubuntu-latest
    
    # データをコミットするために 'contents: write' 権限が必要
    permissions:
      contents: write

    steps:
      - name: Checkout repository (Deep fetch for full history)
        uses: actions/checkout@v4
        with:
          # 行数計測のために完全な履歴を取得
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Matplotlibはデータ収集のみのステップでは不要ですが、
      # グラフ生成スクリプトと統合する場合は必要になります。
      # - name: Install dependencies (必要に応じて)
      #   run: pip install matplotlib

      - name: Run script to collect history data
        # スクリプトのパスに合わせて変更してください
        run: python scripts/collect_history.py 

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # 生成されたデータファイルをコミット
          commit_message: 'Data: Update line count history'
          files: data/line_count_history.json