name: Count LaTeX lines

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Count LaTeX lines safely
        id: count_lines
        run: |
          # LaTeXファイルの行数をカウント
          if lines=$(find . -name "*.tex" -type f -exec wc -l {} + 2>/dev/null | awk '{s+=$1} END {print s}'); then
            # ファイルが存在しない場合 lines は空になるので0に
            if [ -z "$lines" ]; then
              lines=0
            fi
          else
            lines=0
          fi
          echo "LaTeX行数: $lines"
          echo "LINES=$lines" >> $GITHUB_ENV

      - name: Update Google Sheets
        uses: Wakayama-SocSEL/Writing@v1.1
        with:
          spreadsheetId: "1FUisJPN4DtvkgJq8kv_HE5eG1jJMhUnDyV05_cVJIZw"
          worksheetName: "lines"
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          values: ${{ env.LINES }}
