name: Count LaTeX lines and update Google Sheets

on:
  push:
    branches: [ master ]
  workflow_dispatch:   # 手動実行も可能

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 自作アクションを呼び出す
      - name: Count LaTeX lines
        uses: Wakayama-SocSEL/Writing@master   # action.yml があるブランチ

      # Google Sheets に送信
      - name: Update Google Sheets
        uses: Wakayama-SocSEL/Writing@master
        with:
          spreadsheetId: "1FUisJPN4DtvkgJq8kv_HE5eG1jJMhUnDyV05_cVJIZw"
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          range: "lines!A1"
          values: '[["${{ env.LINES }}"]]'

      - name: Debug
        run: |
          echo "LINES=${{ env.LINES }}"
          ls -l
