name: Count LaTeX lines and update Google Sheets

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # 手動実行も可能

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 自作アクションを呼び出す
      - name: Count LaTeX lines
        uses: Wakayama-SocSEL/Writing@master   # action.yml があるブランチ

      # Google Sheets に送信
      - name: Update Google Sheets
        uses: gautamkrishnar/google-sheets-action@v1.1
        with:
          spreadsheetId: "1FUisJPN4DtvkgJq8kv_HE5eG1jJMhUnDyV05_cVJIZw"
          worksheetName: "lines"
          credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
          values: ${{ env.LINES }}
